kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: iskafkamanager
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: ghcr.io/navikt/kafka-manager/kafka-manager:2.2022.06.28_10.32-8669b1a0d98c # See https://github.com/navikt/kafka-manager/packages
  port: 8080
  webproxy: true
  ingresses:
    - https://iskafkamanager.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 05b6c0d2-b6db-4440-96b4-4de66c09b3c6 # teamsykefravr
  kafka:
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [
            {
              "name": "teamsykefravr.aktivitetskrav-vurdering",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
